// lib/compliance/generator.ts
//
// Generates the structured content for all 4 EU AI Act compliance documents.
// Output is stored as JSON in ComplianceDocument.content.
// Rendered to HTML in the browser preview, exported to .docx / .pdf on demand.
//
// Documents generated:
//   1. Acceptable Use Policy        (Article 4)
//   2. AI System Register           (Articles 6–7)
//   3. Staff AI Literacy Records    (Article 4)
//   4. Human Oversight Procedure    (Article 14, HIGH risk only)

import {
  Organization,
  OrganizationAITool,
  TrainingRecord,
  RiskLevel,
  DocumentType,
} from "@prisma/client";
import { trainingTypeLabel } from "@/lib/training-labels";

// ─── Document block types (renderer-agnostic) ────────────────────────────────

export type Block =
  | { type: "heading"; level: 1 | 2 | 3; text: string }
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }
  | { type: "table"; headers: string[]; rows: string[][]; columnWidths?: number[] }
  | { type: "divider" }
  | { type: "signature"; label: string; date: string }
  | { type: "note"; text: string };      // styled callout / info box

export interface GeneratedDocument {
  type: DocumentType;
  title: string;
  subtitle: string;
  organizationName: string;
  generatedAt: string;
  blocks: Block[];
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function today(): string {
  return new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function nextYear(): string {
  const d = new Date();
  d.setFullYear(d.getFullYear() + 1);
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function riskLabel(level: RiskLevel): string {
  const map: Record<RiskLevel, string> = {
    MINIMAL: "Minimal risk",
    LIMITED: "Limited risk",
    HIGH: "High risk",
    UNACCEPTABLE: "Unacceptable (prohibited)",
  };
  return map[level];
}

function categoryLabel(cat: string): string {
  return cat
    .split("_")
    .map((w) => w[0] + w.slice(1).toLowerCase())
    .join(" / ");
}

function dataTypesLabel(types: string[]): string {
  if (!types || types.length === 0) return "Not specified";
  return types
    .map((t) =>
      t
        .split("_")
        .map((w) => w[0] + w.slice(1).toLowerCase())
        .join(" ")
    )
    .join(", ");
}

// ─── Document 1: Acceptable Use Policy ───────────────────────────────────────

export function generateAUP(
  org: Organization,
  tools: OrganizationAITool[]
): GeneratedDocument {
  const approvedTools = tools.filter((t) => t.status === "ACTIVE");
  const highRiskTools = approvedTools.filter((t) => t.riskLevel === RiskLevel.HIGH);
  const limitedRiskTools = approvedTools.filter((t) => t.riskLevel === RiskLevel.LIMITED);
  const accountablePerson = approvedTools.find((t) => t.accountablePerson)?.accountablePerson ?? "[Name of responsible person]";
  const accountableEmail  = approvedTools.find((t) => t.accountableEmail)?.accountableEmail  ?? "[Email]";

  const blocks: Block[] = [
    {
      type: "note",
      text: `This policy was generated by Regulaton on ${today()} based on ${org.name}'s AI tool inventory. Review and adjust to reflect your organisation's specific practices before finalising.`,
    },
    { type: "heading", level: 1, text: "AI Acceptable Use Policy" },
    { type: "heading", level: 2, text: "1. Purpose and Scope" },
    {
      type: "paragraph",
      text: `This Artificial Intelligence Acceptable Use Policy ("Policy") sets out the rules and requirements governing the use of artificial intelligence (AI) tools and systems by ${org.name} ("the Organisation") and all its staff, contractors, and authorised third parties.`,
    },
    {
      type: "paragraph",
      text: "This Policy is issued in accordance with the EU Artificial Intelligence Act (Regulation (EU) 2024/1689) and applies to all AI systems used by the Organisation in its operations, regardless of whether those systems are operated internally or via third-party services.",
    },
    {
      type: "paragraph",
      text: "This Policy applies to all employees, contractors, consultants, and other personnel who access or use AI tools on behalf of the Organisation.",
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "2. Approved AI Tools" },
    {
      type: "paragraph",
      text: `The following AI tools are approved for use within ${org.name}. Staff must not use AI tools not on this list without prior written approval from the AI Compliance Lead. The full AI System Register should be consulted for complete details.`,
    },
    {
      type: "table",
      headers: ["Tool", "Provider", "Category", "Risk Level", "Approved Use"],
      rows: approvedTools.map((t) => [
        (t as any).customName ?? (t as any).libraryTool?.name ?? "Unknown",
        (t as any).libraryTool?.providerCompany ?? t.customProvider ?? "Unknown",
        categoryLabel(t.category),
        riskLabel(t.riskLevel),
        t.usageDescription ?? "General business use",
      ]),
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "3. Permitted Uses" },
    {
      type: "paragraph",
      text: "AI tools approved by the Organisation may be used for the following purposes:",
    },
    {
      type: "list",
      items: [
        "Drafting, editing, and improving internal documents and communications",
        "Researching topics and summarising publicly available information",
        "Writing, reviewing, and explaining code",
        "Analysing business data where no personal data of third parties is involved",
        "Generating marketing copy and creative content for review by a human",
        "Automating repetitive internal tasks as described in the AI System Register",
        "Any other use explicitly approved in writing by the AI Compliance Lead",
      ],
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "4. Prohibited Uses" },
    {
      type: "paragraph",
      text: "The following uses of AI are strictly prohibited within the Organisation:",
    },
    {
      type: "list",
      items: [
        "Entering personal data of customers, employees, or third parties into any AI tool not covered by an appropriate data processing agreement",
        "Using AI to make final decisions about individuals in employment, credit, healthcare, or legal matters without documented human review",
        "Using AI to generate content that impersonates real individuals without their explicit consent",
        "Using AI to create misleading, fraudulent, or deceptive content",
        "Using AI for any purpose prohibited under EU or applicable national law, including the EU AI Act's prohibited AI practices (Article 5)",
        "Using unapproved AI tools on company systems or with company data",
        "Sharing confidential company information, client data, or trade secrets with AI tools",
        ...(highRiskTools.length > 0
          ? ["Using high-risk AI tools (see Section 6) as the sole basis for any consequential decision affecting a person"]
          : []),
      ],
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "5. Data Handling Requirements" },
    {
      type: "paragraph",
      text: "When using approved AI tools, staff must observe the following data handling requirements:",
    },
    {
      type: "list",
      items: [
        "Do not enter names, email addresses, phone numbers, or other personal identifiers into AI tools unless the tool has a signed Data Processing Agreement (DPA) in place",
        "Do not enter special category personal data (health, ethnicity, religion, sexual orientation) into any AI tool",
        "Do not enter financial account details, passwords, API keys, or security credentials",
        "Anonymise or pseudonymise data before using AI tools for analysis wherever possible",
        "Treat AI-generated outputs containing any personal data with the same care as other personal data under the Organisation's GDPR obligations",
        "Check the applicable tool's privacy policy and DPA before processing any customer data",
      ],
    },
    { type: "divider" },

    ...(limitedRiskTools.length > 0
      ? [
          {
            type: "heading" as const,
            level: 2 as const,
            text: "6. Transparency Obligations (Limited Risk Tools)",
          },
          {
            type: "paragraph" as const,
            text: `The Organisation uses ${limitedRiskTools.length} AI tool${limitedRiskTools.length === 1 ? "" : "s"} classified as "limited risk" under the EU AI Act. For these tools, the Act requires transparency with any persons interacting with or affected by the AI:`,
          },
          {
            type: "list" as const,
            items: [
              "Where an AI chatbot or virtual assistant interacts with customers or members of the public, the AI nature of the system must be clearly disclosed at the start of the interaction",
              "Where AI is used to generate written content, images, audio, or video that is presented to the public, this must be labelled as AI-generated where required by law or where there is a reasonable risk of confusion with human or real content",
              "Staff must not represent AI-generated content as their own unassisted work in contexts where this could mislead",
            ],
          },
          { type: "divider" as const },
        ]
      : []),

    ...(highRiskTools.length > 0
      ? [
          {
            type: "heading" as const,
            level: 2 as const,
            text: "7. Human Oversight (High Risk AI Systems)",
          },
          {
            type: "paragraph" as const,
            text: `The Organisation uses ${highRiskTools.length} AI system${highRiskTools.length === 1 ? "" : "s"} classified as high risk under Annex III of the EU AI Act. For these systems, the following requirements apply without exception:`,
          },
          {
            type: "list" as const,
            items: [
              "A named accountable person must be designated for each high-risk AI system (see the Human Oversight Procedure document)",
              "No consequential decision based on high-risk AI output may be made without documented human review",
              "The accountable person must be able to override, interrupt, or disregard AI outputs at any time",
              "All high-risk AI decisions must be logged with sufficient detail to enable retrospective review",
              "Staff using high-risk AI systems must complete specific training on the system's limitations and oversight requirements",
            ],
          },
          { type: "divider" as const },
        ]
      : []),

    { type: "heading", level: 2, text: "8. Staff Training Requirements" },
    {
      type: "paragraph",
      text: "In accordance with Article 4 of the EU AI Act, the Organisation requires all staff who use approved AI tools to complete AI literacy training:",
    },
    {
      type: "list",
      items: [
        "New staff must complete the Organisation's AI literacy induction before using any approved AI tool",
        "All existing staff must complete AI literacy training within 30 days of this Policy's effective date",
        "Training completion must be recorded in the Organisation's Staff AI Literacy Training Records",
        "AI literacy training must be refreshed annually or when significant new AI tools are adopted",
        "Specific training is required before using any high-risk AI system",
      ],
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "9. Approving New AI Tools" },
    {
      type: "paragraph",
      text: "No new AI tool may be used within the Organisation without prior approval. The process is:",
    },
    {
      type: "list",
      items: [
        `Submit a request to ${accountablePerson} (${accountableEmail}) describing the tool, its intended use, and what data it will process`,
        "The AI Compliance Lead will assess the tool's risk level and data handling practices",
        "Tools requiring personal data processing will require a Data Processing Agreement with the vendor before approval",
        "High-risk tools require a documented risk assessment before approval",
        "Approved tools are added to the AI System Register and this Policy is updated",
        "Unapproved tools must not be used on company systems or with company data under any circumstances",
      ],
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "10. Reporting and Incidents" },
    {
      type: "paragraph",
      text: `Report any of the following to ${accountablePerson} immediately:`,
    },
    {
      type: "list",
      items: [
        "An AI tool produced output that was used to make a decision later found to be wrong or harmful",
        "Personal data was accidentally entered into an AI tool",
        "An AI tool behaved unexpectedly or appeared to malfunction",
        "A staff member used an unapproved AI tool with company data",
        "A customer complained about AI-generated content or an AI-assisted decision",
      ],
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "11. Accountability" },
    {
      type: "paragraph",
      text: `The AI Compliance Lead for ${org.name} is responsible for maintaining this Policy, the AI System Register, and staff training records.`,
    },
    {
      type: "table",
      headers: ["Role", "Name", "Contact"],
      rows: [
        ["AI Compliance Lead", accountablePerson, accountableEmail],
        ["Policy Owner", org.name, ""],
      ],
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "12. Review and Updates" },
    {
      type: "paragraph",
      text: `This Policy will be reviewed annually. The next scheduled review is ${nextYear()}. The Policy will also be reviewed whenever significant new AI tools are adopted, or when the EU AI Act guidance is updated in a way that affects the Organisation's obligations.`,
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "13. Effective Date" },
    {
      type: "paragraph",
      text: `This Policy is effective as of ${today()}.`,
    },
    {
      type: "signature",
      label: `${accountablePerson} — AI Compliance Lead, ${org.name}`,
      date: today(),
    },
  ];

  return {
    type: DocumentType.ACCEPTABLE_USE_POLICY,
    title: "AI Acceptable Use Policy",
    subtitle: `EU AI Act Compliance — ${org.name}`,
    organizationName: org.name,
    generatedAt: today(),
    blocks,
  };
}

// ─── Document 2: AI System Register ──────────────────────────────────────────

export function generateRegister(
  org: Organization,
  tools: OrganizationAITool[]
): GeneratedDocument {
  const activeTools = tools.filter((t) => t.status === "ACTIVE");

  const blocks: Block[] = [
    {
      type: "note",
      text: `Auto-generated from ${org.name}'s tool inventory on ${today()}. Review for accuracy before finalising. Update whenever tools are added, removed, or change in use.`,
    },
    { type: "heading", level: 1, text: "AI System Register" },
    {
      type: "paragraph",
      text: `This register documents all artificial intelligence systems in use by ${org.name} as required under the EU Artificial Intelligence Act. It is maintained by the AI Compliance Lead and reviewed at minimum annually.`,
    },
    {
      type: "paragraph",
      text: `Organisation: ${org.name} | Country: ${org.country} | Register date: ${today()} | Next review: ${nextYear()}`,
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "Registered AI Systems" },
    {
      type: "table",
      headers: [
        "System name",
        "Provider",
        "Category",
        "Risk level",
        "Department",
        "Data types processed",
        "Purpose",
        "Accountable person",
        "Vendor AI Act status",
        "Date added",
        "Next review",
      ],
      // 11 columns is a lot for one printed page — give the free-text fields
      // (Data types, Purpose) more room and the short/fixed-format fields
      // (Risk level, dates) less, rather than splitting width evenly.
      columnWidths: [12, 9, 8, 7, 8, 12, 14, 10, 8, 6, 6],
      rows: activeTools.map((t) => {
        const name = (t as any).customName ?? (t as any).libraryTool?.name ?? "Unknown";
        const provider = (t as any).libraryTool?.providerCompany ?? t.customProvider ?? "Unknown";
        const vendorStatus = t.vendorCompliance === true
          ? "Compliant ✓"
          : t.vendorCompliance === false
          ? "Not confirmed"
          : "Not checked";
        const nextReview = t.nextReviewAt
          ? new Date(t.nextReviewAt).toLocaleDateString("en-GB")
          : nextYear();
        return [
          name,
          provider,
          categoryLabel(t.category),
          riskLabel(t.riskLevel),
          t.department ?? "Not specified",
          dataTypesLabel(t.dataTypes),
          t.usageDescription ?? "Not specified",
          t.accountablePerson ?? "Not assigned",
          vendorStatus,
          new Date(t.addedAt).toLocaleDateString("en-GB"),
          nextReview,
        ];
      }),
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "Summary by Risk Level" },
    {
      type: "table",
      headers: ["Risk level", "Count", "Obligations"],
      rows: [
        [
          "Minimal risk",
          String(activeTools.filter((t) => t.riskLevel === RiskLevel.MINIMAL).length),
          "Add to register. Train staff. No further obligations.",
        ],
        [
          "Limited risk",
          String(activeTools.filter((t) => t.riskLevel === RiskLevel.LIMITED).length),
          "Transparency: disclose AI use to affected persons.",
        ],
        [
          "High risk (Annex III)",
          String(activeTools.filter((t) => t.riskLevel === RiskLevel.HIGH).length),
          "Risk management, human oversight, logging, conformity assessment required.",
        ],
      ],
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "Maintenance" },
    {
      type: "list",
      items: [
        "This register must be updated within 30 days of any new AI tool being adopted",
        "Tools that are discontinued must be marked inactive (not deleted, for audit purposes)",
        "The register must be reviewed in full at least annually",
        "A copy of this register must be available to the AI Compliance Lead at all times",
        "Regulators may request access to this register — maintain it in a retrievable format",
      ],
    },
  ];

  return {
    type: DocumentType.AI_SYSTEM_REGISTER,
    title: "AI System Register",
    subtitle: `EU AI Act Compliance — ${org.name}`,
    organizationName: org.name,
    generatedAt: today(),
    blocks,
  };
}

// ─── Document 3: Staff AI Literacy Training Records ──────────────────────────

export function generateTrainingRecord(
  org: Organization,
  trainingRecords: TrainingRecord[]
): GeneratedDocument {
  const blocks: Block[] = [
    {
      type: "note",
      text: "This document serves as the Organisation's official record of staff AI literacy training as required by Article 4 of the EU AI Act. Add a row for each staff member upon training completion.",
    },
    { type: "heading", level: 1, text: "Staff AI Literacy Training Record" },
    {
      type: "paragraph",
      text: `Article 4 of the EU Artificial Intelligence Act requires that organisations ensure their staff have an appropriate level of AI literacy — knowledge of AI systems, their capabilities and limitations, and the risks they may pose. This document records compliance with that obligation for ${org.name}.`,
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "Training Completed" },
    ...(trainingRecords.length > 0
      ? [
          {
            type: "table" as const,
            headers: [
              "Staff member",
              "Email",
              "Training type",
              "Completed",
              "Evidence / notes",
            ],
            columnWidths: [18, 22, 22, 14, 24],
            rows: trainingRecords.map((r) => [
              r.staffName,
              r.staffEmail,
              trainingTypeLabel(r.trainingType),
              new Date(r.completedAt).toLocaleDateString("en-GB"),
              r.evidenceUrl ?? r.notes ?? "Self-declared completion",
            ]),
          } as Block,
        ]
      : [
          {
            type: "paragraph" as const,
            text: "No training records added yet. Add records as staff complete AI literacy training.",
          } as Block,
        ]),
    { type: "divider" },

    { type: "heading", level: 2, text: "What Constitutes AI Literacy Training" },
    {
      type: "paragraph",
      text: "The EU AI Act does not prescribe a specific format. Acceptable training includes:",
    },
    {
      type: "list",
      items: [
        "Internal training sessions covering this Policy and the Organisation's AI tool inventory",
        "External online courses covering AI fundamentals and the EU AI Act (e.g. EU AI Act courses from the EU AI Office, Coursera, LinkedIn Learning)",
        "Vendor-provided training on specific approved AI tools",
        "Reading and acknowledging this Acceptable Use Policy (counts as basic literacy for minimal-risk tools)",
        "For high-risk AI tools: tool-specific training covering the system's purpose, limitations, and human oversight requirements",
      ],
    },
    { type: "divider" },

    { type: "heading", level: 2, text: "Minimum Requirements by Role" },
    {
      type: "table",
      headers: ["Staff type", "Minimum training", "Frequency"],
      rows: [
        ["All staff using AI tools", "AI Acceptable Use Policy acknowledgement + basic AI literacy", "On joining, then annually"],
        ["Staff using limited-risk tools", "Above + transparency obligations training", "Annually"],
        ...(trainingRecords.length > 0 || true
          ? [["Staff using high-risk AI tools", "Above + tool-specific oversight training", "Before first use, then annually"]]
          : []),
      ],
    },
    { type: "divider" },

    {
      type: "signature",
      label: `AI Compliance Lead, ${org.name}`,
      date: today(),
    },
  ];

  return {
    type: DocumentType.LITERACY_TRAINING_RECORD,
    title: "Staff AI Literacy Training Record",
    subtitle: `EU AI Act — Article 4 Compliance — ${org.name}`,
    organizationName: org.name,
    generatedAt: today(),
    blocks,
  };
}

// ─── Document 4: Human Oversight Procedure (HIGH risk tools only) ────────────

export function generateOversightProcedure(
  org: Organization,
  tools: OrganizationAITool[]
): GeneratedDocument {
  const highRiskTools = tools.filter(
    (t) => t.riskLevel === RiskLevel.HIGH && t.status === "ACTIVE"
  );

  const blocks: Block[] = [
    {
      type: "note",
      text: `This document is required under Article 14 of the EU AI Act for each high-risk AI system. ${org.name} currently uses ${highRiskTools.length} high-risk AI system${highRiskTools.length === 1 ? "" : "s"}.`,
    },
    { type: "heading", level: 1, text: "Human Oversight Procedure" },
    {
      type: "paragraph",
      text: `Article 14 of the EU Artificial Intelligence Act requires that high-risk AI systems be deployed with appropriate human oversight measures that allow the persons to whom such systems are assigned to: (a) understand the capabilities and limitations of the system; (b) monitor the system for anomalies; (c) be able to decide not to use the system in a particular situation; and (d) be able to intervene or interrupt the system.`,
    },
    {
      type: "paragraph",
      text: `This document records the human oversight procedures in place for each high-risk AI system operated by ${org.name}.`,
    },
    { type: "divider" },

    ...highRiskTools.flatMap((tool, i): Block[] => {
      const toolName = (tool as any).customName ?? (tool as any).libraryTool?.name ?? "Unknown tool";
      const accountable = tool.accountablePerson ?? "[Name to be assigned]";
      const accountableEmail = tool.accountableEmail ?? "[Email to be assigned]";
      const oversight = tool.oversightProcedure ?? "[Describe how staff review and can override AI decisions made by this tool]";

      return [
        { type: "heading", level: 2, text: `${i + 1}. ${toolName}` },
        {
          type: "table",
          headers: ["Field", "Detail"],
          rows: [
            ["System name", toolName],
            ["Provider", (tool as any).libraryTool?.providerCompany ?? tool.customProvider ?? "Unknown"],
            ["Department", tool.department ?? "Not specified"],
            ["Accountable person", `${accountable} (${accountableEmail})`],
            ["Data processed", dataTypesLabel(tool.dataTypes)],
          ],
        },
        { type: "heading", level: 3, text: "How the system is used" },
        {
          type: "paragraph",
          text: tool.usageDescription ?? "Usage not yet described. Complete the tool profile in the inventory.",
        },
        { type: "heading", level: 3, text: "Human oversight procedure" },
        { type: "paragraph", text: oversight },
        { type: "heading", level: 3, text: "Override and intervention" },
        {
          type: "list",
          items: [
            `The accountable person (${accountable}) has the authority to override, disregard, or suspend use of this system at any time`,
            "Staff must be informed that AI output from this system is advisory, not final",
            "Any decision taken on the basis of this system's output must be reviewed by a human with relevant expertise before action is taken",
            "Staff may decline to follow AI recommendations without needing to justify this to the system",
          ],
        },
        { type: "heading", level: 3, text: "Logging and audit" },
        {
          type: "list",
          items: [
            "Where technically possible, AI outputs and human review decisions must be logged",
            "Logs must be retained for a minimum of 12 months",
            "Logs must be accessible to the AI Compliance Lead on request",
          ],
        },
        { type: "divider" },
      ];
    }),

    ...(highRiskTools.length === 0
      ? [
          {
            type: "paragraph" as const,
            text: "No high-risk AI tools are currently registered. This document will be populated if high-risk tools are added to the inventory.",
          },
        ]
      : []),

    { type: "heading", level: 2, text: "General Principles" },
    {
      type: "list",
      items: [
        "Human oversight is not optional for high-risk AI systems — it is a legal requirement",
        "The accountable person is responsible for ensuring oversight procedures are followed",
        "Staff should receive training specific to each high-risk system before using it",
        "Suspected errors, biases, or anomalous behaviour must be reported immediately",
        "These procedures must be reviewed whenever the system is updated or its use changes",
      ],
    },
    { type: "divider" },
    {
      type: "signature",
      label: `AI Compliance Lead, ${org.name}`,
      date: today(),
    },
  ];

  return {
    type: DocumentType.OVERSIGHT_PROCEDURE,
    title: "Human Oversight Procedure",
    subtitle: `EU AI Act — Article 14 Compliance — ${org.name}`,
    organizationName: org.name,
    generatedAt: today(),
    blocks,
  };
}

// ─── Main entry point ─────────────────────────────────────────────────────────

export function generateDocument(
  type: DocumentType,
  org: Organization,
  tools: OrganizationAITool[],
  trainingRecords: TrainingRecord[]
): GeneratedDocument {
  switch (type) {
    case DocumentType.ACCEPTABLE_USE_POLICY:
      return generateAUP(org, tools);
    case DocumentType.AI_SYSTEM_REGISTER:
      return generateRegister(org, tools);
    case DocumentType.LITERACY_TRAINING_RECORD:
      return generateTrainingRecord(org, trainingRecords);
    case DocumentType.OVERSIGHT_PROCEDURE:
      return generateOversightProcedure(org, tools);
    default:
      throw new Error(`Unknown document type: ${type}`);
  }
}

export function generateAllDocuments(
  org: Organization,
  tools: OrganizationAITool[],
  trainingRecords: TrainingRecord[]
): GeneratedDocument[] {
  return [
    generateAUP(org, tools),
    generateRegister(org, tools),
    generateTrainingRecord(org, trainingRecords),
    generateOversightProcedure(org, tools),
  ];
}
