// app/(marketing)/terms/page.tsx
import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Regulaton",
  description: "Terms governing use of the Regulaton platform.",
};

const EFFECTIVE_DATE = "1 August 2026";
const CONTACT_EMAIL  = "legal@regulaton.com";

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bg)", fontFamily: "Inter, sans-serif" }}>
      <nav style={{ background: "var(--bg-card)", borderBottom: "1px solid var(--border)" }}>
        <div className="px-4 sm:px-6" style={{ maxWidth: 800, margin: "0 auto", height: 56, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <Link href="/" style={{ fontFamily: "IBM Plex Serif, serif", fontSize: 18, fontWeight: 600, color: "var(--text-primary)", textDecoration: "none" }}>
            Regula<span style={{ color: "#059669" }}>ton</span>
          </Link>
          <Link href="/login" className="nav-link-hover" style={{ fontSize: 13, color: "var(--text-secondary)", textDecoration: "none" }}>Sign in</Link>
        </div>
      </nav>

      <div className="px-4 sm:px-6 py-9 sm:py-12" style={{ maxWidth: 720, margin: "0 auto", paddingBottom: 80 }}>
        <div style={{ fontFamily: "IBM Plex Mono, monospace", fontSize: 11, color: "var(--text-muted)", letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 8 }}>
          Legal
        </div>
        <h1 style={{ fontFamily: "IBM Plex Serif, serif", fontSize: 36, fontWeight: 600, color: "var(--text-primary)", margin: "0 0 8px", letterSpacing: "-0.02em" }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", margin: "0 0 40px" }}>
          Effective date: {EFFECTIVE_DATE}
        </p>

        <div style={{
          padding: "16px 20px", background: "#FEF3C7", border: "1px solid #FDE68A",
          borderRadius: 10, fontSize: 13, color: "#78350F", marginBottom: 40, lineHeight: 1.6,
        }}>
          <strong>Important:</strong> Regulaton provides compliance documentation tooling, not legal advice.
          Documents generated by Regulaton are templates based on publicly available regulatory guidance.
          They should be reviewed by a qualified legal professional before reliance in regulated contexts.
        </div>

        <div style={{ fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.75 }}>

          <Section title="1. Acceptance of terms">
            <p>By creating an account or using Regulaton ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you are using the Service on behalf of an organisation, you represent that you have authority to bind that organisation to these Terms.</p>
            <p>If you do not agree to these Terms, do not use the Service.</p>
          </Section>

          <Section title="2. Description of service">
            <p>Regulaton is a software-as-a-service platform that helps small and medium businesses document their AI tool usage and generate compliance documentation related to the EU Artificial Intelligence Act (Regulation (EU) 2024/1689).</p>
            <p><strong>Regulaton is not a law firm and does not provide legal advice.</strong> The documents and assessments generated by Regulaton are based on our interpretation of publicly available regulatory guidance. They do not constitute legal advice and should not be relied upon as such. You are responsible for ensuring your organisation's compliance with applicable laws.</p>
          </Section>

          <Section title="3. Account registration">
            <p>You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account.</p>
            <p>You must be 18 or older to use the Service. You must be authorised to enter into these Terms on behalf of your organisation.</p>
          </Section>

          <Section title="4. Subscription and payment">
            <p><strong>Free trial:</strong> New accounts receive a 14-day free trial with full access to all features. No credit card is required to start a trial.</p>
            <p><strong>Paid plans:</strong> After the trial period, continued use requires a paid subscription. Prices are listed at regulaton.com/pricing and are inclusive of applicable VAT where required.</p>
            <p><strong>Billing:</strong> Subscriptions are billed monthly in advance. Payment is processed by Stripe. By subscribing, you authorise us to charge your payment method on a recurring basis.</p>
            <p><strong>Cancellation:</strong> You may cancel your subscription at any time through the billing portal in your account settings. Cancellation takes effect at the end of the current billing period. We do not provide refunds for partial periods.</p>
            <p><strong>Price changes:</strong> We will give at least 30 days' notice of any price increases via email.</p>
          </Section>

          <Section title="5. Your data and content">
            <p>You retain full ownership of all data and content you input into Regulaton, including your AI tool inventory, compliance documents, and training records ("Your Content").</p>
            <p>By using the Service, you grant Regulaton a limited licence to process Your Content solely to provide the Service to you. We do not use Your Content to train AI models or share it with third parties except as necessary to provide the Service.</p>
            <p>You are responsible for ensuring that Your Content is accurate and that you have the right to input it into the Service.</p>
          </Section>

          <Section title="6. Acceptable use">
            <p>You agree not to:</p>
            <ul style={{ paddingLeft: 20, margin: "8px 0" }}>
              <li style={{ marginBottom: 8 }}>Use the Service for any unlawful purpose or in violation of any applicable laws</li>
              <li style={{ marginBottom: 8 }}>Attempt to reverse engineer, decompile, or extract the source code of the Service</li>
              <li style={{ marginBottom: 8 }}>Use the Service to generate false or misleading compliance documentation</li>
              <li style={{ marginBottom: 8 }}>Resell, sublicence, or otherwise commercialise access to the Service without our written consent</li>
              <li style={{ marginBottom: 8 }}>Use automated tools to access the Service in a way that places unreasonable load on our infrastructure</li>
              <li style={{ marginBottom: 8 }}>Attempt to gain unauthorised access to any part of the Service or its related systems</li>
            </ul>
          </Section>

          <Section title="7. Limitation of liability">
            <p>To the maximum extent permitted by applicable law, Regulaton's total liability to you for any claims arising out of or related to these Terms or the Service shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
            <p>Regulaton shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including lost profits, loss of data, or business interruption.</p>
            <p><strong>Compliance disclaimer:</strong> Regulaton makes no warranty that use of the Service will result in your organisation being compliant with the EU AI Act or any other regulation. Regulatory compliance is your responsibility. Regulaton is a tool to assist you, not a guarantee of compliance.</p>
          </Section>

          <Section title="8. Warranties and disclaimers">
            <p>The Service is provided "as is" and "as available" without warranty of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement.</p>
            <p>We do not warrant that the Service will be uninterrupted, error-free, or that the regulatory guidance reflected in the Service is complete, current, or accurate. EU AI Act guidance continues to evolve, so you should verify current requirements with a qualified advisor.</p>
          </Section>

          <Section title="9. Termination">
            <p>You may close your account at any time by contacting us at <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#1A3A8F" }}>{CONTACT_EMAIL}</a>.</p>
            <p>We may suspend or terminate your account if you breach these Terms, fail to pay, or if we cease operating the Service. We will provide reasonable notice where possible.</p>
            <p>On termination, you may export your data. We will retain your data for 30 days after termination before deletion, except where legally required to retain it.</p>
          </Section>

          <Section title="10. Governing law">
            <p>These Terms are governed by and construed in accordance with the laws of Ireland (EU member state). Any disputes shall be subject to the exclusive jurisdiction of the courts of Ireland, without prejudice to your rights as a consumer under applicable local law.</p>
          </Section>

          <Section title="11. Changes to terms">
            <p>We may update these Terms from time to time. We will notify you of material changes by email at least 14 days in advance. Continued use of the Service after the effective date of changes constitutes acceptance.</p>
          </Section>

          <Section title="12. Contact">
            <p>For questions about these Terms: <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#1A3A8F" }}>{CONTACT_EMAIL}</a></p>
          </Section>

        </div>
      </div>

      <footer style={{ borderTop: "1px solid var(--border)", padding: "24px", textAlign: "center" }}>
        <div style={{ fontSize: 13, color: "var(--text-muted)" }}>
          <Link href="/" className="nav-link-hover" style={{ color: "var(--text-muted)", textDecoration: "none", marginRight: 16 }}>Regulaton</Link>
          <Link href="/terms" className="nav-link-hover" style={{ color: "var(--text-muted)", textDecoration: "none", marginRight: 16 }}>Terms</Link>
          <Link href="/privacy" className="nav-link-hover" style={{ color: "var(--text-muted)", textDecoration: "none" }}>Privacy</Link>
        </div>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2 style={{
        fontFamily: "IBM Plex Serif, serif", fontSize: 20, fontWeight: 600,
        color: "var(--text-primary)", margin: "0 0 12px", letterSpacing: "-0.01em",
      }}>
        {title}
      </h2>
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
        {children}
      </div>
    </div>
  );
}
