// prisma/seed.ts
import { PrismaClient, ToolCategory, RiskLevel } from "@prisma/client";

const prisma = new PrismaClient();

const AI_TOOLS = [
  // ─── Writing & Content ──────────────────────────────────────────────────
  {
    name: "ChatGPT",
    providerCompany: "OpenAI",
    category: ToolCategory.WRITING_CONTENT,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "Limited risk as a general-purpose AI assistant. When deployed in chatbot/customer-facing mode, transparency obligations apply.",
    complianceNotes: "Disclose AI use in any customer-facing context. Document in AI system register. Train staff not to enter personal data.",
    vendorActStatement: true,
    vendorStatementUrl: "https://openai.com/policies/eu-ai-act",
    websiteUrl: "https://chatgpt.com",
    logoSlug: "openai",
  },
  {
    name: "Claude (Anthropic)",
    providerCompany: "Anthropic",
    category: ToolCategory.WRITING_CONTENT,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "General-purpose AI assistant. Limited risk for internal use. Transparency required in customer-facing deployments.",
    complianceNotes: "Same obligations as ChatGPT. Add to AI system register with usage description.",
    vendorActStatement: true,
    websiteUrl: "https://claude.ai",
    logoSlug: "anthropic",
  },
  {
    name: "Gemini",
    providerCompany: "Google",
    category: ToolCategory.WRITING_CONTENT,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "General-purpose AI with transparency obligations in customer-facing use.",
    complianceNotes: "Google has published AI Act compliance positions. Register in AI system register.",
    vendorActStatement: true,
    websiteUrl: "https://gemini.google.com",
    logoSlug: "google",
  },
  {
    name: "Microsoft Copilot",
    providerCompany: "Microsoft",
    category: ToolCategory.WRITING_CONTENT,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "Embedded AI across Microsoft 365. Limited risk in most use cases.",
    complianceNotes: "Microsoft has published extensive EU AI Act documentation. If used in Teams/email for customer communication, ensure AI disclosure.",
    vendorActStatement: true,
    vendorStatementUrl: "https://aka.ms/euaiact",
    websiteUrl: "https://copilot.microsoft.com",
    logoSlug: "microsoft",
  },
  {
    name: "Grammarly",
    providerCompany: "Grammarly",
    category: ToolCategory.WRITING_CONTENT,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "Writing assistance tool. No significant impact on people's rights or safety.",
    complianceNotes: "Minimal obligations. Add to AI system register. Remind staff not to paste sensitive client data into the tool.",
    vendorActStatement: false,
    websiteUrl: "https://grammarly.com",
    logoSlug: "grammarly",
  },
  {
    name: "Jasper",
    providerCompany: "Jasper AI",
    category: ToolCategory.WRITING_CONTENT,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI content generation. If used for content published to customers, synthetic content disclosure obligations may apply.",
    complianceNotes: "If generating marketing copy or articles, consider synthetic content transparency requirements.",
    vendorActStatement: false,
    websiteUrl: "https://jasper.ai",
    logoSlug: "jasper",
  },
  {
    name: "Notion AI",
    providerCompany: "Notion",
    category: ToolCategory.PRODUCTIVITY,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "Internal productivity tool. No customer-facing AI interaction.",
    complianceNotes: "Minimal obligations. Add to register. Ensure data governance policy covers what company information can be entered.",
    vendorActStatement: false,
    websiteUrl: "https://notion.so",
    logoSlug: "notion",
  },
  // ─── Image & Video ───────────────────────────────────────────────────────
  {
    name: "DALL-E",
    providerCompany: "OpenAI",
    category: ToolCategory.IMAGE_VIDEO_GEN,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "Generates synthetic visual content. EU AI Act requires disclosure when synthetic media could be mistaken for real.",
    complianceNotes: "Label AI-generated images when used in public content. Do not use to generate deepfakes.",
    vendorActStatement: true,
    websiteUrl: "https://openai.com/dall-e",
    logoSlug: "openai",
  },
  {
    name: "Midjourney",
    providerCompany: "Midjourney",
    category: ToolCategory.IMAGE_VIDEO_GEN,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI image generation. Synthetic media transparency obligations apply.",
    complianceNotes: "Disclose AI-generated images in marketing/communications.",
    vendorActStatement: false,
    websiteUrl: "https://midjourney.com",
    logoSlug: "midjourney",
  },
  {
    name: "Synthesia",
    providerCompany: "Synthesia",
    category: ToolCategory.IMAGE_VIDEO_GEN,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI video with synthetic human presenters. Deepfake-adjacent technology with transparency obligations.",
    complianceNotes: "Must disclose that videos feature AI-generated avatars, not real people.",
    vendorActStatement: true,
    websiteUrl: "https://synthesia.io",
    logoSlug: "synthesia",
  },
  // ─── Customer Support ────────────────────────────────────────────────────
  {
    name: "Intercom Fin",
    providerCompany: "Intercom",
    category: ToolCategory.CUSTOMER_SUPPORT,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "Customer-facing AI chatbot. Transparency obligations: customers must be informed they're interacting with AI.",
    complianceNotes: "Clearly disclose AI chatbot status at start of every conversation. Provide easy escalation to human agent.",
    vendorActStatement: false,
    websiteUrl: "https://intercom.com",
    logoSlug: "intercom",
  },
  {
    name: "Zendesk AI",
    providerCompany: "Zendesk",
    category: ToolCategory.CUSTOMER_SUPPORT,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI-assisted customer service. Transparency obligations for customer-facing AI.",
    complianceNotes: "Disclose AI involvement when AI drafts responses sent to customers.",
    vendorActStatement: true,
    websiteUrl: "https://zendesk.com",
    logoSlug: "zendesk",
  },
  {
    name: "Tidio",
    providerCompany: "Tidio",
    category: ToolCategory.CUSTOMER_SUPPORT,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI live chat and chatbot platform for customer support.",
    complianceNotes: "Disclose AI chatbot status. Ensure human handoff is available.",
    vendorActStatement: false,
    websiteUrl: "https://tidio.com",
    logoSlug: "tidio",
  },
  // ─── Recruiting & HR — HIGH RISK ────────────────────────────────────────
  {
    name: "HireVue",
    providerCompany: "HireVue",
    category: ToolCategory.RECRUITING_HR,
    defaultRiskLevel: RiskLevel.HIGH,
    riskRationale: "Video interview AI assessment. Explicitly HIGH RISK under Annex III — AI used in employment context to assess, screen or rank job candidates.",
    complianceNotes: "Requires: documented risk management system, human oversight with override capability, logging of AI decisions. Do not use as sole decision-maker.",
    vendorActStatement: true,
    websiteUrl: "https://hirevue.com",
    logoSlug: "hirevue",
  },
  {
    name: "Workable AI",
    providerCompany: "Workable",
    category: ToolCategory.RECRUITING_HR,
    defaultRiskLevel: RiskLevel.HIGH,
    riskRationale: "AI-assisted candidate screening and ranking. HIGH RISK under Annex III for employment AI.",
    complianceNotes: "Requires full Annex III compliance package. Never use AI ranking as final decision without human review.",
    vendorActStatement: true,
    websiteUrl: "https://workable.com",
    logoSlug: "workable",
  },
  {
    name: "LinkedIn Recruiter AI",
    providerCompany: "LinkedIn / Microsoft",
    category: ToolCategory.RECRUITING_HR,
    defaultRiskLevel: RiskLevel.HIGH,
    riskRationale: "AI candidate matching and ranking in a hiring context. HIGH RISK under Annex III.",
    complianceNotes: "Document your oversight process. Do not treat AI match scores as definitive.",
    vendorActStatement: true,
    websiteUrl: "https://linkedin.com/talent",
    logoSlug: "linkedin",
  },
  {
    name: "Personio AI",
    providerCompany: "Personio",
    category: ToolCategory.RECRUITING_HR,
    defaultRiskLevel: RiskLevel.HIGH,
    riskRationale: "HR platform with AI features for recruiting and employee management. HIGH RISK for any AI used in employment decisions.",
    complianceNotes: "Very common in German/EU SMEs. Audit which Personio AI features you use. Assign an accountable person.",
    vendorActStatement: true,
    websiteUrl: "https://personio.com",
    logoSlug: "personio",
  },
  // ─── Finance ─────────────────────────────────────────────────────────────
  {
    name: "Stripe Radar",
    providerCompany: "Stripe",
    category: ToolCategory.FINANCE_ACCOUNTING,
    defaultRiskLevel: RiskLevel.HIGH,
    riskRationale: "AI fraud detection that blocks or flags transactions. Potentially HIGH RISK under Annex III for access to financial services.",
    complianceNotes: "Review whether Stripe Radar's blocking decisions significantly impact EU customers. Document oversight for disputed blocks.",
    vendorActStatement: true,
    websiteUrl: "https://stripe.com/radar",
    logoSlug: "stripe",
  },
  {
    name: "QuickBooks AI",
    providerCompany: "Intuit",
    category: ToolCategory.FINANCE_ACCOUNTING,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "Internal accounting AI for categorisation, forecasting. No significant impact on third-party rights.",
    complianceNotes: "Minimal obligations. Add to register.",
    vendorActStatement: false,
    websiteUrl: "https://quickbooks.intuit.com",
    logoSlug: "intuit",
  },
  {
    name: "Xero AI",
    providerCompany: "Xero",
    category: ToolCategory.FINANCE_ACCOUNTING,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "Internal accounting automation. Low risk — decisions made by the accountant, not the AI.",
    complianceNotes: "Minimal obligations. Register it.",
    vendorActStatement: false,
    websiteUrl: "https://xero.com",
    logoSlug: "xero",
  },
  // ─── Coding ──────────────────────────────────────────────────────────────
  {
    name: "GitHub Copilot",
    providerCompany: "GitHub / Microsoft",
    category: ToolCategory.CODING_DEVELOPMENT,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI coding assistant. No direct impact on end users' rights. Output reviewed by developer before deployment.",
    complianceNotes: "Minimal obligations. Add to register. AI literacy obligation applies — developers must understand AI-generated code must be reviewed.",
    vendorActStatement: true,
    websiteUrl: "https://github.com/features/copilot",
    logoSlug: "github",
  },
  {
    name: "Cursor",
    providerCompany: "Anysphere",
    category: ToolCategory.CODING_DEVELOPMENT,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI-assisted code editor. Developer reviews all output.",
    complianceNotes: "Minimal obligations. Policy on what code/data can be sent to AI for completion is good practice.",
    vendorActStatement: false,
    websiteUrl: "https://cursor.sh",
    logoSlug: "cursor",
  },
  {
    name: "Tabnine",
    providerCompany: "Tabnine",
    category: ToolCategory.CODING_DEVELOPMENT,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI code completion. Can run on-premises for sensitive environments.",
    complianceNotes: "Minimal obligations. Good option for orgs that need on-prem AI.",
    vendorActStatement: false,
    websiteUrl: "https://tabnine.com",
    logoSlug: "tabnine",
  },
  // ─── CRM & Marketing ─────────────────────────────────────────────────────
  {
    name: "HubSpot AI",
    providerCompany: "HubSpot",
    category: ToolCategory.MARKETING,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI content generation, email optimisation, chatbot. Customer-facing chatbot triggers transparency obligations.",
    complianceNotes: "If using HubSpot's AI chatbot on your website: disclose it to users. AI content generation for internal drafts: minimal.",
    vendorActStatement: true,
    websiteUrl: "https://hubspot.com",
    logoSlug: "hubspot",
  },
  {
    name: "Salesforce Einstein",
    providerCompany: "Salesforce",
    category: ToolCategory.MARKETING,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI for CRM — lead scoring, opportunity forecasting, content generation.",
    complianceNotes: "Salesforce has published EU AI Act guidance. If used for lead scoring, document oversight procedure.",
    vendorActStatement: true,
    websiteUrl: "https://salesforce.com/einstein",
    logoSlug: "salesforce",
  },
  {
    name: "Mailchimp AI",
    providerCompany: "Intuit / Mailchimp",
    category: ToolCategory.MARKETING,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI email content generation and send-time optimisation. Internal marketing tool.",
    complianceNotes: "Minimal AI Act obligations. Standard email marketing GDPR requirements already apply.",
    vendorActStatement: false,
    websiteUrl: "https://mailchimp.com",
    logoSlug: "mailchimp",
  },
  // ─── Productivity ─────────────────────────────────────────────────────────
  {
    name: "Zoom AI Companion",
    providerCompany: "Zoom",
    category: ToolCategory.PRODUCTIVITY,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI that records, transcribes, and summarises meetings. Affects third parties — transparency required.",
    complianceNotes: "Inform all meeting participants that AI is recording and transcribing. Required under both AI Act and GDPR.",
    vendorActStatement: true,
    websiteUrl: "https://zoom.us",
    logoSlug: "zoom",
  },
  {
    name: "Slack AI",
    providerCompany: "Slack / Salesforce",
    category: ToolCategory.PRODUCTIVITY,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI summarisation of internal Slack conversations. Internal tool, no customer-facing AI interaction.",
    complianceNotes: "Minimal obligations. Internal use only.",
    vendorActStatement: false,
    websiteUrl: "https://slack.com",
    logoSlug: "slack",
  },
  {
    name: "Google Workspace AI",
    providerCompany: "Google",
    category: ToolCategory.PRODUCTIVITY,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI embedded in Google Docs, Gmail, Sheets. Primarily internal productivity use.",
    complianceNotes: "Minimal for internal use. Google has published AI Act documentation.",
    vendorActStatement: true,
    websiteUrl: "https://workspace.google.com",
    logoSlug: "google",
  },
  {
    name: "Otter.ai",
    providerCompany: "Otter.ai",
    category: ToolCategory.PRODUCTIVITY,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI transcription of meetings. Affects meeting participants who may not know they're being transcribed.",
    complianceNotes: "Always inform meeting participants that Otter.ai is recording and transcribing.",
    vendorActStatement: false,
    websiteUrl: "https://otter.ai",
    logoSlug: "otter",
  },
  // ─── Analytics ───────────────────────────────────────────────────────────
  {
    name: "Hotjar AI",
    providerCompany: "Hotjar",
    category: ToolCategory.DATA_ANALYTICS,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI analysis of user behaviour on websites. Used internally to improve product.",
    complianceNotes: "Minimal AI Act obligations. Standard GDPR cookie consent requirements apply.",
    vendorActStatement: false,
    websiteUrl: "https://hotjar.com",
    logoSlug: "hotjar",
  },
  {
    name: "Amplitude AI",
    providerCompany: "Amplitude",
    category: ToolCategory.DATA_ANALYTICS,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "Product analytics with AI insights. Internal analytical tool.",
    complianceNotes: "Minimal obligations. Add to register.",
    vendorActStatement: false,
    websiteUrl: "https://amplitude.com",
    logoSlug: "amplitude",
  },
  // ─── Research ─────────────────────────────────────────────────────────────
  {
    name: "Perplexity AI",
    providerCompany: "Perplexity",
    category: ToolCategory.RESEARCH,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI search and research assistant. Internal use for research.",
    complianceNotes: "Minimal obligations. Do not input confidential client data.",
    vendorActStatement: false,
    websiteUrl: "https://perplexity.ai",
    logoSlug: "perplexity",
  },
  // ─── Legal ───────────────────────────────────────────────────────────────
  {
    name: "Harvey AI",
    providerCompany: "Harvey",
    category: ToolCategory.LEGAL,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI for legal work. Human lawyer must review all AI output before it's used.",
    complianceNotes: "Ensure all AI-generated legal documents are reviewed by a qualified lawyer before use.",
    vendorActStatement: false,
    websiteUrl: "https://harvey.ai",
    logoSlug: "harvey",
  },
  // ─── Translation ──────────────────────────────────────────────────────────
  {
    name: "DeepL",
    providerCompany: "DeepL",
    category: ToolCategory.TRANSLATION,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI translation tool. No significant impact on rights or safety. Human reviews translations.",
    complianceNotes: "Minimal obligations. Do not translate confidential documents containing personal data unless using DeepL Pro plan.",
    vendorActStatement: false,
    websiteUrl: "https://deepl.com",
    logoSlug: "deepl",
  },
  {
    name: "Google Translate",
    providerCompany: "Google",
    category: ToolCategory.TRANSLATION,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI translation. Minimal risk in business context.",
    complianceNotes: "Caution: free tier has no DPA. Do not use for personal data translation.",
    vendorActStatement: false,
    websiteUrl: "https://translate.google.com",
    logoSlug: "google",
  },
  // ─── Voice & Audio ────────────────────────────────────────────────────────
  {
    name: "ElevenLabs",
    providerCompany: "ElevenLabs",
    category: ToolCategory.VOICE_AUDIO,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI voice synthesis and cloning. Synthetic media transparency obligations.",
    complianceNotes: "Label any AI-generated audio/voice content used publicly. Do not clone voices without explicit consent.",
    vendorActStatement: false,
    websiteUrl: "https://elevenlabs.io",
    logoSlug: "elevenlabs",
  },
  {
    name: "Fireflies.ai",
    providerCompany: "Fireflies",
    category: ToolCategory.VOICE_AUDIO,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI meeting transcription. Affects all meeting participants.",
    complianceNotes: "Inform all participants before recording. Same obligations as Otter.ai.",
    vendorActStatement: false,
    websiteUrl: "https://fireflies.ai",
    logoSlug: "fireflies",
  },
  // ─── Design ───────────────────────────────────────────────────────────────
  {
    name: "Adobe Firefly",
    providerCompany: "Adobe",
    category: ToolCategory.IMAGE_VIDEO_GEN,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI image generation. Synthetic media transparency obligations apply.",
    complianceNotes: "Adobe Firefly is trained on licensed content. Still disclose AI-generated visuals in public-facing content.",
    vendorActStatement: true,
    websiteUrl: "https://firefly.adobe.com",
    logoSlug: "adobe",
  },
  {
    name: "Canva AI",
    providerCompany: "Canva",
    category: ToolCategory.IMAGE_VIDEO_GEN,
    defaultRiskLevel: RiskLevel.LIMITED,
    riskRationale: "AI design and image generation tools embedded in Canva.",
    complianceNotes: "Label AI-generated content when used publicly.",
    vendorActStatement: false,
    websiteUrl: "https://canva.com",
    logoSlug: "canva",
  },
  // ─── Project Management ───────────────────────────────────────────────────
  {
    name: "Asana AI",
    providerCompany: "Asana",
    category: ToolCategory.PRODUCTIVITY,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI project management assistant. Internal productivity tool.",
    complianceNotes: "Minimal obligations. Register it.",
    vendorActStatement: false,
    websiteUrl: "https://asana.com",
    logoSlug: "asana",
  },
  // ─── SEO ──────────────────────────────────────────────────────────────────
  {
    name: "Semrush AI",
    providerCompany: "Semrush",
    category: ToolCategory.MARKETING,
    defaultRiskLevel: RiskLevel.MINIMAL,
    riskRationale: "AI-powered SEO and marketing analytics. Internal tool.",
    complianceNotes: "Minimal obligations. Add to register.",
    vendorActStatement: false,
    websiteUrl: "https://semrush.com",
    logoSlug: "semrush",
  },
];

async function main() {
  console.log("Seeding AI tools library...");
  let created = 0;
  let skipped = 0;

  for (const tool of AI_TOOLS) {
    const existing = await prisma.aIToolLibrary.findUnique({
      where: { name: tool.name },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.aIToolLibrary.create({ data: tool });
    created++;
  }

  console.log(`✓ ${created} tools created, ${skipped} already existed`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
